language: cpp
dist: trusty
sudo: true
os: linux

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -y install qt57base binutils zlib1g-dev libqt5opengl5-dev
  
script:
  - source /opt/qt57/bin/qt57-env.sh
  - qmake -v
  - mkdir Tiled ; cd Tiled/
  - qmake ../tiled.pro
  - make || true # make[1]: /opt/qt57/bin/lrelease: Command not found
  - rm -rf src/
  - mv bin/* . && rm -r bin/ # Workaround for https://github.com/probonopd/linuxdeployqt/issues/14
  - cd ../
  - cp LICENSE* COPYING *md build/
  - cp ./tiled.desktop build/
  - cp ./src/tiled/images/32x32/tiled.png build/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/1/linuxdeployqt-1-x86_64.AppImage"
  - chmod a+x linuxdeployqt-1-x86_64.AppImage
  - ./linuxdeployqt-1-x86_64.AppImage ./Tiled/tiled -appimage -verbose=2
  - curl --upload-file ./Tiled.AppImage https://transfer.sh/Tiled.AppImage # Replace with your deployment mechanism
